FROM node:latest as builder
WORKDIR /app
COPY package*.json ./
RUN npm i
COPY . .
RUN npm run build

FROM nginx as production-stage
RUN mkdir app
COPY --from=builder /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 9001